# The Docker image that will be used to build your app
image: public.ecr.aws/docker/library/python:3.12
# Functions that should be executed before the build script is run
before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
pages:
  script:
    - make build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
