packages:
  - src/installer/cdk
  - src/core/cdk
  - src/core/runtime
  - src/deployments/cdk
  - src/deployments/runtime
  - src/lib/cdk-accelerator
  - src/lib/cdk-constructs
  - src/lib/cdk-plugin-assume-role
  - src/lib/common
  - src/lib/common-config
  - src/lib/common-outputs
  - src/lib/common-types
  - src/lib/config
  - src/lib/config-i18n
  - src/lib/custom-resources/*
  - src/lib/custom-resources/*/*
  - src/lib/io-ts-annotations
  - src/lib/io-ts-json-schema-gen
  - src/lib/docs-gen
