AWSTemplateFormatVersion: "2010-09-09"
Description: "Firewall Security VPC for FortiGate AA for GC CAP (1.0)"


Parameters:
  AvailabilityZoneA:
    Description: Availability Zone A
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ca-central-1a
  AvailabilityZoneB:
    Description: Availability Zone B
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ca-central-1b
  CIDRVPC1:
    Description: CIDR of the VPC
    Type: String
    Default: "100.97.0.0/16"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRPublicZoneSubnetA:
    Description: CIDR of Public Zone Subnet in Availability Zone A (TGW VPN attachments will be located here)
    Type: String
    Default: "100.97.1.0/26"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRPublicZoneSubnetB:
    Description: CIDR of Public Zone Subnet in Availability Zone B (TGW VPN attachments will be located here)
    Type: String
    Default: "100.97.1.64/26"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRManagementZoneSubnetA:
    Description: CIDR of Management Zone Subnet in Availability Zone A
    Type: String
    Default: "100.97.1.128/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRManagementZoneSubnetB:
    Description: CIDR of Management Zone Subnet in Availability Zone B
    Type: String
    Default: "100.97.1.144/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRPrivateZoneSubnetA:
    Description: CIDR of Private Zone Subnet in Availability Zone A
    Type: String
    Default: "100.97.1.160/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRPrivateZoneSubnetB:
    Description: CIDR of Private Zone Subnet in Availability Zone B
    Type: String
    Default: "100.97.1.176/28"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRDMZZoneSubnetA:
    Description: CIDR of DMZ Zone Subnet in Availability Zone A
    Type: String
    Default: "100.97.0.0/25"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28
  CIDRDMZZoneSubnetB:
    Description: CIDR of DMZ Zone Subnet in Availability Zone B
    Type: String
    Default: "100.97.0.128/25"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR must be in the form x.x.x.x/16-28

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: CIDRVPC1
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC,Ref: "AWS::StackName"]]
  SubnetPublicZoneA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRPublicZoneSubnetA
      AvailabilityZone:
        Ref: AvailabilityZoneA
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Public-A Subnet]]
  SubnetPublicZoneB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRPublicZoneSubnetB
      AvailabilityZone:
        Ref: AvailabilityZoneB
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Public-B Subnet]]
  SubnetManagementZoneA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRManagementZoneSubnetA
      AvailabilityZone:
        Ref: AvailabilityZoneA
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Management-A Subnet]]
  SubnetManagementZoneB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRManagementZoneSubnetB
      AvailabilityZone:
        Ref: AvailabilityZoneB
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Management-B Subnet]]
  SubnetPrivateZoneA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRPrivateZoneSubnetA
      AvailabilityZone:
        Ref: AvailabilityZoneA
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Private-A Subnet]]
  SubnetPrivateZoneB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRPrivateZoneSubnetB
      AvailabilityZone:
        Ref: AvailabilityZoneB
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Private-B Subnet]]
  SubnetDMZZoneA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRDMZZoneSubnetA
      AvailabilityZone:
        Ref: AvailabilityZoneA
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", DMZ-A Subnet]]
  SubnetDMZZoneB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: CIDRDMZZoneSubnetB
      AvailabilityZone:
        Ref: AvailabilityZoneB
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", DMZ-B Subnet]]
  RouteTablePublicSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Public Route Table]]
  RouteTablePublicSubnetAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePublicSubnet
      SubnetId:
        Ref: SubnetPublicZoneA
  RouteTablePublicSubnetAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePublicSubnet
      SubnetId:
        Ref: SubnetPublicZoneB
  RouteTableManagementSubnetA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Management-A Route Table]]
  RouteTableManagementSubnetAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableManagementSubnetA
      SubnetId:
        Ref: SubnetManagementZoneA
  RouteTableManagementSubnetB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Management-B Route Table]]
  RouteTableManagementSubnetAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableManagementSubnetB
      SubnetId:
        Ref: SubnetManagementZoneB
  RouteTablePrivateSubnetA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Private-A Route Table]]
  RouteTablePrivateAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePrivateSubnetA
      SubnetId:
        Ref: SubnetPrivateZoneA
  RouteTablePrivateSubnetB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", Private-B Route Table]]
  RouteTablePrivateSubnetAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePrivateSubnetB
      SubnetId:
        Ref: SubnetPrivateZoneB
  RouteTableDMZSubnetA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", DMZ-A Route Table]]
  RouteTableDMZAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableDMZSubnetA
      SubnetId:
        Ref: SubnetDMZZoneA
  RouteTableDMZSubnetB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, Ref: "AWS::StackName", DMZ-B Route Table]]
  RouteTableDMZAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableDMZSubnetB
      SubnetId:
        Ref: SubnetDMZZoneB
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join ["-", [FGVPC, "AWS::StackName", IGW]]
  AttachGatewayIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  RouteInternetviaIGW:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTablePublicSubnet


Outputs:
  AvailabilityZoneA:
    Description: "Availability Zone A"
    Value: !Ref AvailabilityZoneA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-AvailabilityZoneA"
  AvailabilityZoneB:
    Description: "Availability Zone B"
    Value: !Ref AvailabilityZoneB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-AvailabilityZoneB"
  VPC:
    Description: "VPC"
    Value: !Ref VPC
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-VPC"
  CIDRVPC1:
    Description: "VPC CIDR"
    Value: !Ref CIDRVPC1
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-VPC-CIDRBLOCK"
  SubnetPublicZoneA:
    Description: "Public Zone Subnet A"
    Value: !Ref SubnetPublicZoneA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPublicZoneA"
  CIDRPublicZoneSubnetA:
    Description: "Public Zone Subnet A CIDR"
    Value: !Ref CIDRPublicZoneSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPublicZoneA-CIDRBLOCK"
  SubnetPublicZoneB:
    Description: "Public Zone Subnet B"
    Value: !Ref SubnetPublicZoneB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPublicZoneB"
  CIDRPublicZoneSubnetB:
    Description: "Public Zone Subnet B CIDR"
    Value: !Ref CIDRPublicZoneSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPublicZoneB-CIDRBLOCK"
  SubnetManagementZoneA:
    Description: "Management Zone Subnet A"
    Value: !Ref SubnetManagementZoneA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetManagementZoneA"
  CIDRManagementZoneSubnetA:
    Description: "Management Zone Subnet A CIDR"
    Value: !Ref CIDRManagementZoneSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetManagementZoneA-CIDRBLOCK"
  SubnetManagementZoneB:
    Description: "Management Zone Subnet B"
    Value: !Ref SubnetManagementZoneB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetManagementZoneB"
  CIDRManagementZoneSubnetB:
    Description: "Management Zone Subnet B CIDR"
    Value: !Ref CIDRManagementZoneSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetManagementZoneB-CIDRBLOCK"
  SubnetPrivateZoneA:
    Description: "Private Zone Subnet A"
    Value: !Ref SubnetPrivateZoneA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPrivateZoneA"
  CIDRPrivateZoneSubnetA:
    Description: "Private Zone Subnet A CIDR"
    Value: !Ref CIDRPrivateZoneSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-PrivateZoneSubnetA-CIDRBLOCK"
  SubnetPrivateZoneB:
    Description: "Private Zone Subnet B"
    Value: !Ref SubnetPrivateZoneB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetPrivateZoneB"
  CIDRPrivateZoneSubnetB:
    Description: "Private Zone Subnet B CIDR"
    Value: !Ref CIDRPrivateZoneSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-PrivateZoneSubnetB-CIDRBLOCK"
  SubnetDMZZoneA:
    Description: "DMZ Zone Subnet A"
    Value: !Ref SubnetDMZZoneA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetDMZZoneA"
  CIDRDMZZoneSubnetA:
    Description: "DMZ Zone Subnet A CIDR"
    Value: !Ref CIDRDMZZoneSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-DMZZoneSubnetA-CIDRBLOCK"
  SubnetDMZZoneB:
    Description: "DMZ Zone Subnet B"
    Value: !Ref SubnetDMZZoneB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-SubnetDMZZoneB"
  CIDRDMZZoneSubnetB:
    Description: "DMZ Zone Subnet B CIDR"
    Value: !Ref CIDRDMZZoneSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-DMZZoneSubnetB-CIDRBLOCK"
  RouteTablePublicSubnet:
    Description: "Public Route Table"
    Value: !Ref RouteTablePublicSubnet
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTablePublicSubnet"
  RouteTableManagementSubnetA:
    Description: "Management-A Route Table"
    Value: !Ref RouteTableManagementSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTableManagementSubnetA"
  RouteTableManagementSubnetB:
    Description: "Management-B Route Table"
    Value: !Ref RouteTableManagementSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTableManagementSubnetB"
  RouteTablePrivateSubnetA:
    Description: "Private-A Route Table"
    Value: !Ref RouteTablePrivateSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTablePrivateSubnetA"
  RouteTablePrivateSubnetB:
    Description: "Private-B Route Table"
    Value: !Ref RouteTablePrivateSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTablePrivateSubnetB"
  RouteTableDMZSubnetA:
    Description: "DMZ-A Route Table"
    Value: !Ref RouteTableDMZSubnetA
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTableDMZSubnetA"
  RouteTableDMZSubnetB:
    Description: "DMZ-B Route Table"
    Value: !Ref RouteTableDMZSubnetB
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-RouteTableDMZSubnetB"
  InternetGateway:
    Description: "Internet Gateway"
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "FGVPC-${AWS::StackName}-InternetGateway"
