name: Prettier
on: [pull_request]

jobs:
  prettier:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Prettier
        run: |
          npm install -g prettier
      - name: Check if all files are pretty
        run: |
          prettier --check **/*.ts
