on:
  release:
    types: [published]

name: Merge Release Branch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Format Branch Name
        id: format
        env:
          GITHUB_REF: ${{ github.ref }} # This will be the tag; i.e. ref/tags/v1.1.1
        run: |
          git fetch --tags
          echo ::set-output name=branch_name::"release/$(echo "${GITHUB_REF}" | cut -d/ -f3-)"
      - name: Fetch main
        run: |
          git fetch origin
          git checkout ${{ steps.format.outputs.branch_name }}
          git checkout main
      - name: Merge release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge ${{ steps.format.outputs.branch_name }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
